### ISSUE TITLE
System crahes with task['id']

### ISSUE THREAD

**Issue by hvaldecantos** [hvaldecantos/pcer#30]
```
(pcer) $ python pcer/main.py 
1080
ParticipantForm.loadCurrentParticipantStatus
None
ParticipantForm.onLoadButtonClick
ParticipantForm.onContinueButtonClick
(u'123', u'oo')
1080
SystemForm.onShowTaskButtonClick
1080
Traceback (most recent call last):
  File "/home/hector/Work/python/pcer/pcer/experiment_controller.py", line 47, in show_task_form
    self.window = TaskForm(self.experiment)
  File "/home/hector/Work/python/pcer/pcer/task_form.py", line 16, in __init__
    super(TaskForm, self).__init__(experiment)
  File "/home/hector/Work/python/pcer/pcer/pcer_window.py", line 22, in __init__
    self.initUI() # invokes method in subclass
  File "/home/hector/Work/python/pcer/pcer/task_form.py", line 26, in initUI
    self.group_box, self.choice_combo_question_list = self.experiment.form_builder.build_task_form(task)
  File "/home/hector/Work/python/pcer/pcer/form_builder.py", line 55, in build_task_form
    task_id = task['id']
TypeError: 'NoneType' object has no attribute '__getitem__'
Aborted (core dumped)

```

**Comment by hvaldecantos** [comment]
commit sha 8dbfea48e25a4bf334e2a83150fcde27983e057f fixed it
